---
title: "Violins body and end vs rapamycin"
author: "Manfred Schmid"
date: "9 August 2017"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE, fig.path = 'Figures_violins_body_and_end_vs_rapa/', dev='pdf')
```

```{r, message=FALSE,warning=FALSE}
suppressWarnings(library('tidyverse'))
suppressWarnings(library('magrittr'))
suppressWarnings(library('knitr'))
suppressWarnings(library('broom'))
```


### load the counts

-> from script body_end_counting.Rmd  
-> her we only look at length-normalized BGsub data
```{r}
load('data/norm_signal_body_end_pA+_pA-_BGsub.RData', verbose=TRUE)
```


#### violin plot fun
```{r}
violin_plot <- function(df) {
  ggplot(df, aes(x=rapa, y=scaled_reads, fill=rapa)) +
  geom_violin() +
  geom_boxplot(fill='gray', width=.2, outlier.shape = NA) +
  facet_grid(fraction~strain+part_pA+rep) +
  scale_y_log10() +
  scale_fill_brewer(palette = 'Set1') +
  theme_bw()
}
```


# Violin plots

```{r}
(body_pAminus <- filter(both_df, pA == 'pA-', part == 'body') %>%
  dplyr::mutate(part_pA = 'body_pA_minus') %>%
   dplyr::select(-Pap, -pA, -part, -sum))
```

```{r}
(end_pAplus <- filter(both_df, pA == 'pA+', part == 'end') %>%
  dplyr::mutate(part_pA = 'end_pA_plus') %>%
   dplyr::select(-Pap, -pA, -part, -sum))
```


```{r}
(df <- bind_rows(body_pAminus, end_pAplus))
```


```{r violins ORF-T body pAminus vs end pAplus}
v <- df %>%
  filter(type == 'ORF-T', rapa != 70) %>%
  violin_plot(.)

v
```


```{r violins ORF-T body pAminus vs end pAplus without replicates}
v +
  facet_grid(fraction~strain+part_pA)
```


```{r}
sessionInfo()
```



