---
title: "Published decay rate measures"
author: "Manfred Schmid"
output:
  pdf_document: default
  html_document: default
---

`r format(Sys.time(), "%d %B, %Y")`

```{r setup, echo=TRUE}
knitr::opts_chunk$set(
  fig.width = 12,
  fig.height = 8,
  fig.path = paste0('Figures_published_decay_estimates/'),
  dev = 'pdf',
  echo = TRUE,
  warning = FALSE,
  message = FALSE,
  tidy = TRUE,
  error = TRUE
  )
```



```{r load packages, echo=T, warning=F, message=F}
suppressWarnings(library(tidyverse))
suppressWarnings(library(magrittr))
suppressWarnings(library(LSD))
```


## Loading half-life datasets

#### DTA 

from Miller et al., Molecular Systems Biology 7:458, 2010
```{r}
(
  miller <-
    read_tsv(
      '/Users/schmidm/Documents/genomewide_datasets/halflife_and_transcription_rates/Cramer_DTA/Cramer_half-life.txt',
      col_names = TRUE
    ) %>%
    mutate(Miller_DR = log(2) / halflife0) %>%
    dplyr::select(name, Miller_DR)
)
```


#### cDTA 

from Sun et al., Mol. Cell 52, 52–62, 2013
```{r}
sun <-
  read_tsv(
    '/Users/schmidm/Documents/genomewide_datasets/halflife_and_transcription_rates/Cramer_cDTA_Sun2013/Cramer_decay_rates.txt',
    col_names = TRUE
  )

sun <- sun[, c(1, 3)]
colnames(sun) <- c('name', 'Sun_DR')
(sun %<>% mutate(Sun_DR = as.numeric(sub(',', '.', Sun_DR))))
```


```{r}
DR_literature <- left_join(miller, sun)
```

```{r heatscatter Sun vs Miller}
heatscatter(DR_literature$Miller_DR, DR_literature$Sun_DR, xlim=c(0,.6), ylim=c(0,.6), cor=TRUE)
```

```{r}
cor(DR_literature$Miller_DR, DR_literature$Sun_DR, use='pairwise.complete')
```

```{r}
cor(DR_literature$Miller_DR, DR_literature$Sun_DR, use='pairwise.complete', method='spearman')
```


#### Presnyak

from Presnyak et al., 2015, Cell 160, 1111–1124
```{r}
(
  presnyak <-
    read_tsv(
      '/Users/schmidm/Documents/genomewide_datasets/halflife_and_transcription_rates/Coller_half_life/Coller_halflife.txt',
      col_names = TRUE,
      locale = locale(decimal_mark = ",")
    ) %>%
    dplyr::rename(name = Gene_ID) %>%
    mutate(
      Presnyak_pA_DR = log(2) / pA_Half_life,
      Presnyak_total_DR =  log(2) / Total_Half_life
    ) %>%
    dplyr::select(name, Presnyak_pA_DR, Presnyak_total_DR)
) 
```


```{r}
DR_literature %<>% left_join(., presnyak)
```

```{r heatscatter Sun vs PresnyakpA}
heatscatter(DR_literature$Presnyak_pA_DR, DR_literature$Sun_DR, xlim=c(0,1), ylim=c(0,1), cor=TRUE)
```

```{r heatscatter Sun vs Presnyaktotal}
heatscatter(DR_literature$Presnyak_total_DR, DR_literature$Sun_DR, xlim=c(0,1), ylim=c(0,1), cor=TRUE)
```

```{r heatscatter Miller vs PresnyakpA}
heatscatter(DR_literature$Presnyak_pA_DR, DR_literature$Miller_DR, xlim=c(0,1), ylim=c(0,1), cor=TRUE)
```

```{r heatscatter Miller vs Presnyaktotal}
heatscatter(DR_literature$Presnyak_total_DR, DR_literature$Miller_DR, xlim=c(0,1), ylim=c(0,1), cor=TRUE)
```



```{r}
save(DR_literature, file='../../data/published_decay_estimates.RData')
```


```{r}
sessionInfo()
```
